on: push

jobs:
  format:
    name: formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: npm install prettier
      - run: node ./node_modules/.bin/prettier '**/*.md'
      - name: git setting
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "github-actions[bot]"
      - name: Commit files
        run: |
          git add .
          git commit -m "format" -a
          git pull
          git push origin ${GITHUB_REF_NAME}
